import { ScoringResult } from './scoring.js';

export function generateMarkdownSummary(result: ScoringResult): string {
  const statusEmoji = result.passed ? '✅' : '❌';

  let summary = `### AgentProof PR Readiness Report\n\n`;
  summary += `**Status:** ${statusEmoji} ${result.passed ? 'PASSED' : 'FAILED'}\n`;
  summary += `**Readiness Score:** ${result.normalizedScore}/100\n\n`;

  if (!result.passed) {
    if (result.blockersFailed) {
      summary += `> ⚠️ **Action Required:** One or more blocking rules failed.\n\n`;
    } else {
      summary += `> ⚠️ **Action Required:** The readiness score is below the minimum required.\n\n`;
    }
  }

  summary += `#### Rule Breakdown\n\n`;
  summary += `| Rule | Status | Score | Message |\n`;
  summary += `| :--- | :---: | :---: | :--- |\n`;

  for (const r of result.ruleResults) {
    const icon = r.passed ? '✅' : r.isBlocking ? '❌' : '⚠️';
    summary += `| ${r.name} | ${icon} | ${r.score}/${r.maxScore} | ${r.message}${r.details ? `<br/>_${r.details}_` : ''} |\n`;
  }

  summary += `\n---\n*Generated by [AgentProof PR](https://github.com/mattfred/agentproof-pr)*`;

  return summary;
}

export function generatePRComment(result: ScoringResult, minimumScore: number): string {
  const marker = '<!-- agentproof-pr-comment -->';
  const status = result.passed ? 'Ready' : 'Not Ready';

  let comment = `# AgentProof PR Readiness\n\n`;
  comment += `**Status:** ${status}\n`;
  comment += `**Score:** ${result.normalizedScore}/100\n\n`;

  const blockingIssues = result.ruleResults.filter((r) => r.isBlocking && !r.passed);

  if (result.normalizedScore < minimumScore) {
    blockingIssues.push({
      id: 'minimum_score',
      name: 'minimum_score',
      passed: false,
      score: 0,
      maxScore: 0,
      message: `Readiness score ${result.normalizedScore} is below the minimum required score of ${minimumScore}.`,
      isBlocking: true,
    });
  }

  if (blockingIssues.length > 0) {
    comment += `## Blocking Issues\n\n`;
    for (const r of blockingIssues) {
      comment += `* ${r.message}\n`;
    }
    comment += `\n`;
  }

  const warnings = result.ruleResults.filter((r) => !r.isBlocking && !r.passed);
  if (warnings.length > 0) {
    comment += `## Warnings\n\n`;
    for (const r of warnings) {
      comment += `* ${r.message}\n`;
    }
    comment += `\n`;
  }

  const passedChecks = result.ruleResults.filter((r) => r.passed);
  if (passedChecks.length > 0) {
    comment += `## Passed Checks\n\n`;
    for (const r of passedChecks) {
      comment += `* ${r.message}\n`;
    }
    comment += `\n`;
  }

  const suggestedFixes = result.ruleResults.filter((r) => !r.passed && r.details);
  if (suggestedFixes.length > 0) {
    comment += `## Suggested Fixes\n\n`;
    for (const r of suggestedFixes) {
      comment += `* ${r.details}\n`;
    }
    comment += `\n`;
  }

  comment += `${marker}\n`;
  return comment;
}
