import { ScoringResult } from './scoring.js';

export function generateMarkdownSummary(result: ScoringResult): string {
  const statusEmoji = result.passed ? '✅' : '❌';
  const scoreColor = result.normalizedScore >= 80 ? 'green' : result.normalizedScore >= 60 ? 'yellow' : 'red';

  let summary = `### AgentProof PR Readiness Report\n\n`;
  summary += `**Status:** ${statusEmoji} ${result.passed ? 'PASSED' : 'FAILED'}\n`;
  summary += `**Readiness Score:** ${result.normalizedScore}/100\n\n`;

  if (!result.passed) {
    if (result.blockersFailed) {
      summary += `> ⚠️ **Action Required:** One or more blocking rules failed.\n\n`;
    } else {
      summary += `> ⚠️ **Action Required:** The readiness score is below the minimum required.\n\n`;
    }
  }

  summary += `#### Rule Breakdown\n\n`;
  summary += `| Rule | Status | Score | Message |\n`;
  summary += `| :--- | :---: | :---: | :--- |\n`;

  for (const r of result.ruleResults) {
    const icon = r.passed ? '✅' : r.isBlocking ? '❌' : '⚠️';
    summary += `| ${r.name} | ${icon} | ${r.score}/${r.maxScore} | ${r.message}${r.details ? `<br/>_${r.details}_` : ''} |\n`;
  }

  summary += `\n---\n*Generated by [AgentProof PR](https://github.com/mattfred/agentproof-pr)*`;

  return summary;
}
